### ISSUE TITLE
Test Code Comprehensive

### ISSUE THREAD

**Issue by Suphakinfraser** [veevism/SE327-Metrics#3]

**Comment by webwebweb5** [comment]
requests-html: 
https://github.com/psf/requests-html
- Coverage: 71.0%
- Pylint: Your code has been rated at 7.87/10

**Comment by webwebweb5** [comment]
Pytube: 
https://github.com/pytube/pytube
- Coverage: 72.6%
- Pylint: Your code has been rated at 9.20/10

**Comment by webwebweb5** [comment]
Grab: 
https://github.com/lorien/grab
- Coverage: 5.5%
- Pylint: Your code has been rated at 9.14/10

**Comment by webwebweb5** [comment]
scrapy:
https://github.com/scrapy/scrapy 
- Coverage: 0.0%
- Pylint: Your code has been rated at 10.00/10
