### ISSUE TITLE
Calculate The Test Result

### ISSUE THREAD

**Issue by Suphakinfraser** [veevism/SE327-Metrics#6]

**Comment by thiwakonsakunchao** [comment]
### **Document Comprehensive**

**Requests-HTML:**

- Completeness (8/10):
- Clarity (9/10):
- Accuracy (10/10):
- Consistency (9/10):
- Integrity (10/10):
- Keyword Completeness (7/10):
- Avg score: 8.83

**Pytube:**

- Completeness: 7/10.
- Clarity: 8/10
- Accuracy: 8/10
- Consistency: 8/10
- Integrity: 7/10
- Keyword Completeness: 6/10
- Avg score: 7.33

**Grab:**

- Completeness: 6/10
- Clarity: 8/10
- Accuracy: 9/10
- Consistency: 7/10
- Integrity: 9/10
- Keyword Completeness: 7/10
- Avg score: 7.67

**Scrap:**

- Completeness (8/10):
- Clarity (10/10):
- Accuracy (9/10):
- Consistency (9/10):
- Integrity (9/10):
- Keyword Completeness (8/10):
- Avg score: 88.3


### **Reusability in term of code**

Pylint:
- requests-html: Pylint: Your code has been rated at 7.87/10
- pytube: Pylint: Your code has been rated at 9.20/10
- Scrapy: Your code has been rated at 10.00/10
- Grab: Your code has been rated at 9.14/10

### **Reusability in term of built**

Pylint: 

- requests-html: Pylint: Your code has been rated at 7.87/10
- pytube: Pylint: Your code has been rated at 9.20/10
- Scrapy: Your code has been rated at 10.00/10
- Grab: Your code has been rated at 9.14/10

### **Activeness Of Development Team**

- Requests-html: AS (Activeness score) 
 ( 4*0.4 + 3*1 + 2*0 + 1*1) /  ( 4+3+2+1) =  0.56
- pytube: AS (Activeness score) 
 ( 4*14 + 3*69 + 2*424 + 1*2.1) /  ( 4+3+2+1) = 111.31
- Scrapy: AS (Activeness score)
 ( 4*10 + 3*240 + 2*475 + 1*10.3) /  ( 4+3+2+1) = 172.03
- Grab: AS (Activeness score)
 ( 4*24 + 3*1 + 2*0 + 1*0.28) /  ( 4+3+2+1) = 9.928

**Comment by thiwakonsakunchao** [comment]
d163bd227e4aa5ba54fec7b0abdedb8773ea8f9f
